module.exports = {
    ACTION_TYPE:["VISITA", "EMAIL", "LLAMADA", "REUNIÓN", "OTRO"],
    CATEGORY_NAME:[
        "AGRO-JARDINERIA Y COMPOSICIONES FLORALES",
        "DESARROLLO DE APLICACIONES WEB",
        "EDUCACIÓN INFANTIL",
        "GESTIÓN FORESTAL Y DEL MEDIO NATURAL",
        "INTEGRACIÓN SOCIAL",
        "PRODUCCIÓN AGROECOLÓGICA",
        "SISTEMAS MICROINFORMÁTICOS Y REDES"
    ],
    DOCUMENT_TYPE:["GENERAL", "MANUAL", "DECRETO/ORDEN/CURRÍCULUM", "CURRÍCULUM VITAE", "OTRO", "AVATAR"],
    DUMMY_TYPE:["TEXTO", "NUMERO", "BOOLEANO", "OTRO"],
    JOB_STATUS:["ACTIVA", "CERRADA", "EN PROGRESO"],
    USER_PROFILES:["ADMINISTRADOR","PROFESOR","ALUMNO","EMPRESA"]
}



